version: '3.8'

  services:
    traefik:
      image: traefik:v3.0
      container_name: traefik
      restart: always
      networks:
        - web
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/traefik.toml:/etc/traefik/traefik.toml
        - ./data/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml
        - ./data/acme.json:/acme.json

  networks:
    web:
      external: true

